from src.core.enums import CommandsEnum

COMMAND_DESCRIPTIONS_RU: dict[CommandsEnum, str] = {
    CommandsEnum.START: "Начать",
    CommandsEnum.HELP: "Помощь",
    CommandsEnum.ROLE: "Выбрать роль",
    CommandsEnum.GENERAL_SETTINGS: "Общие настройки",
    CommandsEnum.FULL_NAME_PANEL: "ФИО",
    CommandsEnum.SET_FULL_NAME: "Установить ФИО",
    CommandsEnum.STUDENT_ROLE: "Студент",
    CommandsEnum.STUDENT_HOMEWORKS: "Посмотреть задания",
    CommandsEnum.STUDENT_ANSWERS: "Посмотреть ответы",
    CommandsEnum.STUDENT_GROUP: "Текущая группа",
    CommandsEnum.TEACHER_ROLE: "Преподаватель",
    CommandsEnum.TEACHER_HOMEWORKS: "Посмотреть задания",
    CommandsEnum.TEACHER_HOMEWORK_CREATE: "Создать задание",
    CommandsEnum.TEACHER_GROUPS: "Посмотреть группы",
    CommandsEnum.TEACHER_GROUP_CREATE: "Создать группу",
    CommandsEnum.TEACHER_GROUP_EDIT: "Редактировать",
    CommandsEnum.TEACHER_GROUP_DELETE: "Удалить",
    CommandsEnum.TEACHER_GROUP_GET_LINK: "Получить ссылку",
    CommandsEnum.ADMIN_PANEL: "Админ-панель",
    CommandsEnum.ADMIN_STUDENTS: "Студенты",
    CommandsEnum.ADMIN_GROUPS: "Группы",
    CommandsEnum.ADMIN_TEACHERS: "Преподаватели",
    CommandsEnum.ADMIN_BAN_USER: "Заблокировать пользователя",
    CommandsEnum.ADMIN_UNBAN_USER: "Разблокировать пользователя",
    CommandsEnum.BACK: "Назад",
    CommandsEnum.CANCEL: "Отмена",
}
